Compiled from "CWE397_Throw_Generic__throw_Exception_01.java"
public class testcases.CWE397_Throw_Generic.CWE397_Throw_Generic__throw_Exception_01 extends testcasesupport.AbstractTestCase {
  public testcases.CWE397_Throw_Generic.CWE397_Throw_Generic__throw_Exception_01();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method testcasesupport/AbstractTestCase."<init>":()V
       4: return

  public void bad() throws java.lang.Exception;
    Code:
       0: new           #7                  // class java/lang/Exception
       3: dup
       4: invokespecial #9                  // Method java/lang/Exception."<init>":()V
       7: athrow

  private void good1() throws java.io.FileNotFoundException;
    Code:
       0: new           #10                 // class java/io/FileNotFoundException
       3: dup
       4: invokespecial #12                 // Method java/io/FileNotFoundException."<init>":()V
       7: athrow

  public void good() throws java.io.FileNotFoundException;
    Code:
       0: aload_0
       1: invokevirtual #13                 // Method good1:()V
       4: return

  public static void main(java.lang.String[]) throws java.lang.ClassNotFoundException, java.lang.InstantiationException, java.lang.IllegalAccessException;
    Code:
       0: aload_0
       1: invokestatic  #18                 // Method mainFromParent:([Ljava/lang/String;)V
       4: return
}
